// Generated by scripts/generateCampaignLevels.ts — do not edit by hand.
import { bstInsert, cloneTree, type TreeNode } from "./tree";
import type { Level } from "./scoring";

export interface HardcodedCampaignSpec {
  id: string;
  title: string;
  blurb: string;
  difficulty: Level["difficulty"];
  insertOrder: number[];
  parRotations: number;
  optimalPath: Level["optimalPath"];
  threshold2: number;
  threshold3: number;
}

export const HARDCODED_CAMPAIGN_SPECS: HardcodedCampaignSpec[] = [
  {
    "id": "c01",
    "title": "First Turn",
    "blurb": "One rotation from calm — learn the left pivot.",
    "difficulty": "tutorial",
    "insertOrder": [
      1,
      2,
      3
    ],
    "parRotations": 1,
    "optimalPath": [
      {
        "type": "L",
        "nodeId": "n-1"
      }
    ],
    "threshold2": 1.7,
    "threshold3": 2.8
  },
  {
    "id": "c02",
    "title": "The Zigzag",
    "blurb": "A hooked left child asks for two precise turns.",
    "difficulty": "tutorial",
    "insertOrder": [
      3,
      1,
      2
    ],
    "parRotations": 2,
    "optimalPath": [
      {
        "type": "L",
        "nodeId": "n-1"
      },
      {
        "type": "R",
        "nodeId": "n-3"
      }
    ],
    "threshold2": 1.7,
    "threshold3": 2.8
  },
  {
    "id": "c03",
    "title": "Lean Right",
    "blurb": "A short chain tilting right. Unwind it cleanly.",
    "difficulty": "easy",
    "insertOrder": [
      1,
      2,
      3,
      4,
      5
    ],
    "parRotations": 2,
    "optimalPath": [
      {
        "type": "L",
        "nodeId": "n-1"
      },
      {
        "type": "L",
        "nodeId": "n-2"
      }
    ],
    "threshold2": 1.5,
    "threshold3": 2.5
  },
  {
    "id": "c04",
    "title": "Lean Left",
    "blurb": "The mirror spine — depth without symmetry.",
    "difficulty": "easy",
    "insertOrder": [
      5,
      4,
      3,
      2,
      1
    ],
    "parRotations": 2,
    "optimalPath": [
      {
        "type": "R",
        "nodeId": "n-5"
      },
      {
        "type": "R",
        "nodeId": "n-4"
      }
    ],
    "threshold2": 1.5,
    "threshold3": 2.5
  },
  {
    "id": "c05",
    "title": "Six Pack",
    "blurb": "Six nodes, six degrees of skew. No free passes.",
    "difficulty": "easy",
    "insertOrder": [
      1,
      2,
      3,
      4,
      5,
      6
    ],
    "parRotations": 3,
    "optimalPath": [
      {
        "type": "L",
        "nodeId": "n-1"
      },
      {
        "type": "L",
        "nodeId": "n-2"
      },
      {
        "type": "L",
        "nodeId": "n-4"
      }
    ],
    "threshold2": 1.5,
    "threshold3": 2.5
  },
  {
    "id": "c06",
    "title": "The Press",
    "blurb": "Seven in a right chain — the workshop signature.",
    "difficulty": "medium",
    "insertOrder": [
      1,
      2,
      3,
      4,
      5,
      6,
      7
    ],
    "parRotations": 3,
    "optimalPath": [
      {
        "type": "L",
        "nodeId": "n-1"
      },
      {
        "type": "L",
        "nodeId": "n-2"
      },
      {
        "type": "L",
        "nodeId": "n-4"
      }
    ],
    "threshold2": 1.4,
    "threshold3": 2.3
  },
  {
    "id": "c07",
    "title": "The Counterpress",
    "blurb": "Seven stacked left. Same length, opposite fault.",
    "difficulty": "medium",
    "insertOrder": [
      7,
      6,
      5,
      4,
      3,
      2,
      1
    ],
    "parRotations": 3,
    "optimalPath": [
      {
        "type": "R",
        "nodeId": "n-7"
      },
      {
        "type": "R",
        "nodeId": "n-6"
      },
      {
        "type": "R",
        "nodeId": "n-4"
      }
    ],
    "threshold2": 1.4,
    "threshold3": 2.3
  },
  {
    "id": "c08",
    "title": "Nested Fault",
    "blurb": "Local hooks at multiple depths — read before you rotate.",
    "difficulty": "medium",
    "insertOrder": [
      2,
      1,
      7,
      3,
      6,
      4,
      5
    ],
    "parRotations": 3,
    "optimalPath": [
      {
        "type": "R",
        "nodeId": "n-7"
      },
      {
        "type": "L",
        "nodeId": "n-2"
      },
      {
        "type": "R",
        "nodeId": "n-7"
      }
    ],
    "threshold2": 1.4,
    "threshold3": 2.3
  },
  {
    "id": "c09",
    "title": "Criss-Cross",
    "blurb": "Alternating inserts tangle the crown. Five moves minimum.",
    "difficulty": "hard",
    "insertOrder": [
      1,
      7,
      2,
      6,
      3,
      5,
      4
    ],
    "parRotations": 5,
    "optimalPath": [
      {
        "type": "R",
        "nodeId": "n-7"
      },
      {
        "type": "L",
        "nodeId": "n-1"
      },
      {
        "type": "R",
        "nodeId": "n-7"
      },
      {
        "type": "R",
        "nodeId": "n-6"
      },
      {
        "type": "L",
        "nodeId": "n-2"
      }
    ],
    "threshold2": 1.35,
    "threshold3": 2.2
  },
  {
    "id": "c10",
    "title": "Wide Weave",
    "blurb": "Eight nodes with a braided midsection — deceptive balance.",
    "difficulty": "hard",
    "insertOrder": [
      8,
      4,
      2,
      6,
      1,
      3,
      7,
      5
    ],
    "parRotations": 2,
    "optimalPath": [
      {
        "type": "R",
        "nodeId": "n-8"
      },
      {
        "type": "R",
        "nodeId": "n-8"
      }
    ],
    "threshold2": 1.35,
    "threshold3": 2.2
  },
  {
    "id": "c11",
    "title": "Nine Patch",
    "blurb": "A compact nine-node lattice. Efficiency matters.",
    "difficulty": "hard",
    "insertOrder": [
      5,
      4,
      9,
      2,
      7,
      1,
      8,
      3,
      6
    ],
    "parRotations": 2,
    "optimalPath": [
      {
        "type": "R",
        "nodeId": "n-4"
      },
      {
        "type": "R",
        "nodeId": "n-9"
      }
    ],
    "threshold2": 1.35,
    "threshold3": 2.2
  },
  {
    "id": "c12",
    "title": "Long Spine",
    "blurb": "Nine nodes in a left chain — longest walk in the folio.",
    "difficulty": "expert",
    "insertOrder": [
      9,
      8,
      7,
      6,
      5,
      4,
      3,
      2,
      1
    ],
    "parRotations": 5,
    "optimalPath": [
      {
        "type": "R",
        "nodeId": "n-9"
      },
      {
        "type": "R",
        "nodeId": "n-8"
      },
      {
        "type": "R",
        "nodeId": "n-6"
      },
      {
        "type": "R",
        "nodeId": "n-7"
      },
      {
        "type": "R",
        "nodeId": "n-4"
      }
    ],
    "threshold2": 1.3,
    "threshold3": 2.1
  },
  {
    "id": "c13",
    "title": "Master Class",
    "blurb": "Nine-node right spine. The heaviest sheet in the set.",
    "difficulty": "expert",
    "insertOrder": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9
    ],
    "parRotations": 5,
    "optimalPath": [
      {
        "type": "L",
        "nodeId": "n-1"
      },
      {
        "type": "L",
        "nodeId": "n-2"
      },
      {
        "type": "L",
        "nodeId": "n-4"
      },
      {
        "type": "L",
        "nodeId": "n-3"
      },
      {
        "type": "L",
        "nodeId": "n-6"
      }
    ],
    "threshold2": 1.3,
    "threshold3": 2.1
  }
];

function treeFromInsertOrder(values: number[]): TreeNode {
  let root: TreeNode | null = null;
  for (const v of values) root = bstInsert(root, v);
  if (!root) throw new Error("empty insert order");
  return root;
}

export const CAMPAIGN_LEVELS: Level[] = HARDCODED_CAMPAIGN_SPECS.map((spec) => {
  const scrambledTree = cloneTree(treeFromInsertOrder(spec.insertOrder));
  if (!scrambledTree) throw new Error(`clone failed ${spec.id}`);
  return {
    id: spec.id,
    n: spec.insertOrder.length,
    scrambledTree,
    parRotations: spec.parRotations,
    parExact: true,
    optimalPath: spec.optimalPath,
    threshold2: spec.threshold2,
    threshold3: spec.threshold3,
    difficulty: spec.difficulty,
    title: spec.title,
    blurb: spec.blurb,
  };
});

export function getCampaignLevel(id: string): Level | undefined {
  return CAMPAIGN_LEVELS.find((level) => level.id === id);
}

export function getCampaignLevelIndex(id: string): number {
  return CAMPAIGN_LEVELS.findIndex((level) => level.id === id);
}
